### PR TITLE
add multi process download support

### PR DESCRIPTION
**Pull request by trim21**
重写了所有的website_object.down函数,为了避免在main_loop中使用闭包和额外定义两个函数.

### CODE REVIEW

**Comment by trim21** [comment]
多进程对调试有一些不利,就算指定1进程也是会新开一个进程来进行下载,有些错误信息可能不会输出

**Comment by XIAZY** [comment]
DM5 的问题你修正了吗？
测试过了我就 merge 了

**Comment by XIAZY** [comment]
看起来没修。我直接 merge 了
`+        soup_box = self.flyleaf_soup.findAll('downdiv', {'class': 'relativeRec'})`
这里的意义是什么？

**Comment by XIAZY** [comment]
说真的，你自己都没测试过吧？
-t 好歹要转 int 啊

**Comment by XIAZY** [comment]
/Users/bill/Documents/PythonStuff/DriveIt/driveit.py -u http://comic.ck101.com/comic/3098 -t 10
學園默示錄 / 学園黙示録 HIGHSCHOOL OF THE DEAD - 驚悚 - 卡提諾×揪漫畫, total 22 chapters detected.
Traceback (most recent call last):
  File "/Users/bill/Documents/PythonStuff/DriveIt/driveit.py", line 72, in <module>
    main_loop(ref_box, fetch_latest)
  File "/Users/bill/Documents/PythonStuff/DriveIt/driveit.py", line 29, in main_loop
    pool.map(website_object.down, jobs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 385, in _handle_tasks
    put(task)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.5/site-packages/bs4/element.py", line 702, in __getnewargs__
    return (str(self),)
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by trim21** [comment]
我是测试过dmzj的，但是我现在手头的ss都挂了，ck101和ehentai都没法测试

**Comment by XIAZY** [comment]
DM5 的我修复完了，merge 因为bug太多修复不过来我先姑且回滚
新开一个issue吧

**Pull request merged**
